version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
        interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
